/**
 * @file tk2DD4hep.cc
 * @brief Orchestrates DD4hep compact XML generation from a tracker material budget.
 */

#include <tk2DD4hep.hh>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <time.h>
#include <unistd.h>
#include <pwd.h>

namespace insur {

void tk2DD4hep::translate(MaterialTable& mt, MaterialBudget& mb,
                           XmlTags& trackerXmlTags,
                           const std::string& xmlOutputPath,
                           const std::string& xmlOutputName) {

  const bool isPixelTracker = mb.getTracker().isPixelTracker();

  ex.analyse(mt, mb, trackerXmlTags, trackerData, otstData, false);

  // Build a simple header comment for the output file.
  std::ostringstream header;
  header << "  Generated by tkLayout DD4hep exporter\n";
  header << "  Config: " << xmlOutputName << "\n";
  {
    time_t now = time(nullptr);
    char buf[32];
    if (strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", localtime(&now)))
      header << "  Date: " << buf << "\n";
  }
  {
    struct passwd* pw = getpwuid(getuid());
    if (pw) header << "  User: " << pw->pw_gecos << " (" << pw->pw_name << ")\n";
  }
  wr.setSimpleHeader(header.str());

  // Output file name: tracker_dd4hep.xml (OT) or pixel_dd4hep.xml (IT).
  const std::string fileName = isPixelTracker ? "pixel_dd4hep.xml" : "tracker_dd4hep.xml";
  const std::string filePath = xmlOutputPath + fileName;

  std::ofstream out(filePath);
  if (out.fail())
    throw std::runtime_error("tk2DD4hep::translate: cannot open " + filePath);

  wr.tracker(trackerData, out, isPixelTracker, trackerXmlTags);

  if (out.fail())
    throw std::runtime_error("tk2DD4hep::translate: write error on " + filePath);

  out.close();
  std::cout << "DD4hep compact XML written to " << filePath << std::endl;
}

} // namespace insur
